Puroguramu.App/Pages/CreateExercices.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains.Repository;

namespace Puroguramu.App.Pages;

[ValidateAntiForgeryToken]
[Authorize(Policy = "IsTeacher")]
public class CreateExercices : PageModel
{
    private readonly IExercisesRepository _exercisesRepository;

    public CreateExercices(IExercisesRepository exercisesRepository) => _exercisesRepository = exercisesRepository;

    public string ReturnUrl { get; set; }

    [BindProperty] public InputModel Input { get; set; }

    [BindProperty(SupportsGet = true)] public string LeconTitre { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var reslut = await _exercisesRepository.CreateExerciceAsync(LeconTitre, Input.Titre);
        if (!reslut)
        {
            //Afficher un message d'erreur
            ModelState.AddModelError("Input.Titre", "L'exercice existe déjà");
            return Page();
        }

        ReturnUrl = "/EditLecon";
        return RedirectToPage(ReturnUrl, new { LeconTitre });
    }

    public class InputModel
    {
        [Required(ErrorMessage = "Le champ titre est requis")]
        [RegularExpression(@"^(?!.*<|>).*.{5,}$", ErrorMessage = "Le titre doit contenir au moins 5 caractères et ne doit pas inclure les symboles <>.")]
        public string Titre { get; set; }
    }
}

Puroguramu.App/Pages/CreateLecons.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains.Repository;

namespace Puroguramu.App.Pages;

[ValidateAntiForgeryToken]
[Authorize(Policy = "IsTeacher")]
public class CreateLecons : PageModel
{
    private ILeconsRepository _leconsRepository;

    public CreateLecons(ILeconsRepository leconsRepository) => _leconsRepository = leconsRepository;

    public string ReturnUrl { get; set; }

    [BindProperty] public InputModel Input { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (ModelState.IsValid)
        {
            Console.WriteLine("Titre: " + Input.Titre);
            var add = await _leconsRepository.CreateLecon(Input.Titre);
            if (add)
            {
                return RedirectToPage("/Dashboard");
            }

            ModelState.AddModelError("Input.Titre", "Une leçon avec ce titre existe déjà.");
        }

        return Page();
    }

    public class InputModel
    {
        [Required(ErrorMessage = "Le champ titre est requis")]
        [RegularExpression(@"^(?!.*<|>).*.{5,}$", ErrorMessage = "Le titre doit contenir au moins 5 caractères et ne doit pas inclure les symboles <>.")]
        public string Titre { get; set; }
    }
}

Puroguramu.App/Pages/DashBoard.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains;
using Puroguramu.Domains.Repository;
using Puroguramu.Infrastructures.dto;
using Role = Puroguramu.Infrastructures.dto.Role;

namespace Puroguramu.App.Pages;

[ValidateAntiForgeryToken]
public class DashBoard : PageModel
{
    private readonly ILeconsRepository _leconsRepository;
    private readonly UserManager<Utilisateurs> _userManager;

    public DashBoard(ILeconsRepository leconsRepository, UserManager<Utilisateurs> userManager)
    {
        _leconsRepository = leconsRepository;
        _userManager = userManager;
    }

    [BindProperty(SupportsGet = true)] public string TitreCours { get; set; }

    public List<Lecon> Lecons { get; set; }

    public async Task OnGetAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        ViewData["Role"] = user.Role;
        if (user.Role == Role.Teacher)
        {
            Lecons = _leconsRepository.GetLeconsForCours(user.Id).ToList();
            var nombreEtudiants = _userManager.Users.Count(e => e.Role == Role.Student);
            foreach (var lecon in Lecons)
            {
                lecon.ExercicesFait = _leconsRepository.GetExercicesFait(lecon.Titre);
                lecon.ExercicesTotal = nombreEtudiants;
            }
        }
        else if (user.Role == Role.Student)
        {
            Lecons = _leconsRepository.GetLeconsForCours(user.Id).Where(l => l.EstVisible).ToList();
        }
    }

    public async Task<IActionResult> OnPostProchainExerciceAsync()
    {
        var user = _userManager.GetUserAsync(User).Result;
        var prochainExercice = await _leconsRepository.GetNextExerciceAsync(user.Id);
        Console.WriteLine(prochainExercice);
        if (prochainExercice.Item1 == string.Empty || prochainExercice.Item2 == string.Empty)
        {
            //Afficher un pop-up pas d'exercice disponible
            return RedirectToPage();
        }

        return RedirectToPage("/Exercice", new { Titre = prochainExercice.Item1, LeconTitre = prochainExercice.Item2 });
    }

    public async Task<IActionResult> OnPostReprendreExercicesAsync()
    {
        // Logique pour reprendre les exercices
        var user = _userManager.GetUserAsync(User).Result;
        var prochainExercice = await _leconsRepository.GetActualExercicesAsync(user.Id);
        if (prochainExercice.Item1 == string.Empty || prochainExercice.Item2 == string.Empty)
        {
            //Afficher un pop-up pas d'exercice disponible
            return RedirectToPage();
        }

        return RedirectToPage("/Exercice", new { Titre = prochainExercice.Item1, LeconTitre = prochainExercice.Item2 });
    }

    public async Task<IActionResult> OnPostChangeVisibilityAsync(string leconTitre)
    {
        await _leconsRepository.ToggleVisibilityLecon(leconTitre);
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostDeleteLeconAsync(string leconTitre)
    {
        await _leconsRepository.DeleteLecon(leconTitre);
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostMoveLeconAsync(string leconTitre, string direction)
    {
        await _leconsRepository.MoveLecon(leconTitre, direction);
        return RedirectToPage();
    }
}

Puroguramu.App/Pages/EditExercice.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains;
using Puroguramu.Domains.Repository;

namespace Puroguramu.App.Pages;

[ValidateAntiForgeryToken]
[Authorize(Policy = "IsTeacher")]
public class EditExercice : PageModel
{
    private readonly IExercisesRepository _exercisesRepository;
    private readonly IAssessExercise _assessor;

    public EditExercice(IExercisesRepository exercisesRepository, IAssessExercise assessor)
    {
        _exercisesRepository = exercisesRepository;
        _assessor = assessor;
    }

    public string ReturnUrl { get; set; }

    [BindProperty] public InputModel Input { get; set; }

    [BindProperty(SupportsGet = true)] public string LeconTitre { get; set; }

    [BindProperty(SupportsGet = true)] public string ExerciceTitre { get; set; }

    public void OnGet()
    {
        var exercice = _exercisesRepository.GetExercise(LeconTitre, ExerciceTitre);
        Input = new InputModel { Titre = exercice.Titre, Enonce = exercice.Enonce, Modele = exercice.Modele, Solution = exercice.Solution, Difficulte = exercice.Difficulte};
    }

    public IActionResult OnPost()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var exercice = _exercisesRepository.GetExercise(LeconTitre, ExerciceTitre);
        var tempTitre = exercice.Titre;
        exercice.Titre = Input.Titre;
        exercice.Enonce = Input.Enonce;
        exercice.Difficulte = Input.Difficulte;
        exercice.Modele = Input.Modele;
        exercice.Solution = Input.Solution;

        var test = _assessor.Assess(exercice, Input.Solution).Result;
        var success = true;
        foreach (var s in test.TestResults)
        {
            //Afficher les erreurs
            if (s.Status == TestStatus.Passed)
            {
                continue;
            }

            ModelState.AddModelError("Input.Solution", s.ErrorMessage);
            success = false;
        }

        if (success)
        {
            var res = _exercisesRepository.UpdateExercise(exercice,tempTitre, LeconTitre);
            if (res.Result)
            {
                _exercisesRepository.updateStatus(LeconTitre,Input.Titre);
                return RedirectToPage("/EditLecon", new { LeconTitre });
            }

            ModelState.AddModelError("Input.Titre", "Le titre de l'exercice existe déjà");
        }

        return Page();
    }

    public class InputModel
    {
        [Required(ErrorMessage = "Le champ titre est requis")]
        [RegularExpression(@"^(?!.*<|>).*.{5,}$", ErrorMessage = "Le titre doit contenir au moins 5 caractères et ne doit pas inclure les symboles <>.")]
        public string Titre { get; set; }

        [Required(ErrorMessage = "Le champ enoncé est requis")]
        [RegularExpression(@"^(?!.*<|>).*.{5,}$", ErrorMessage = "L'énoncé doit contenir au moins 5 caractères et ne doit pas inclure les symboles <>.")]
        public string Enonce { get; set; }

        [Required(ErrorMessage = "Le champ difficulte est requis")]
        [RegularExpression(@"^(?!.*<|>).*.{5,}$", ErrorMessage = "L'énoncé doit contenir au moins 5 caractères et ne doit pas inclure les symboles <>.")]
        public string Difficulte { get; set; }

        [Required(ErrorMessage = "Le champ modele est requis")]
        public string Modele { get; set; }

        [Required(ErrorMessage = "Le champ solution est requis")]
        public string Solution { get; set; }
    }
}

Puroguramu.App/Pages/EditLecon.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains;
using Puroguramu.Domains.Repository;
using Puroguramu.Infrastructures.dto;

namespace Puroguramu.App.Pages;

[ValidateAntiForgeryToken]
[Authorize(Policy = "IsTeacher")]
public class EditLecon : PageModel
{
    private readonly IExercisesRepository _exercisesRepository;
    private readonly ILeconsRepository _leconsRepository;
    private readonly UserManager<Utilisateurs> _userManager;


    public EditLecon(ILeconsRepository leconsRepository, UserManager<Utilisateurs> userManager, IExercisesRepository exercisesRepository)
    {
        _leconsRepository = leconsRepository;
        _userManager = userManager;
        _exercisesRepository = exercisesRepository;
    }

    public string ReturnUrl { get; set; }

    [BindProperty]
    public InputModel Input { get; set; }

    [BindProperty(SupportsGet = true)]
    public string LeconTitre { get; set; }

    public Lecon Lecon { get; set; }

    public async void OnGetAsync()
    {
        Lecon = _leconsRepository.GetLecon(LeconTitre);
        Input = new InputModel { Titre = Lecon.Titre, Description = Lecon.Description };
    }

    public IActionResult OnPost()
    {
        if (ModelState.IsValid)
        {
            var verif = _leconsRepository.UpdateLecon(LeconTitre, Input.Titre, Input.Description); //TODO: possibilité de changer que le titre ou la description
            if (!verif.Result)
            {
                ModelState.AddModelError("Input.Titre", "Le titre de la leçon existe déjà");
                return Page();
            }

            return RedirectToPage("/EditLecon", new { LeconTitre = Input.Titre });
        }
        Lecon = _leconsRepository.GetLecon(LeconTitre);

        return Page();
    }

    public async Task<IActionResult> OnPostDeleteExerciceAsync(string leconTitre, string exerciceTitre)
    {
        var verif = await _exercisesRepository.DeleteExercice(leconTitre, exerciceTitre);
        if (!verif)
        {
            //TODO: Afficher un message d'erreur
            /*Lecon = _leconsRepository.GetLecon(LeconTitre);
            return Page();*/
        }

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostChangeVisibilityAsync(string leconTitre, string exerciceTitre)
    {
        var verif = await _exercisesRepository.ChangeVisibility(leconTitre, exerciceTitre);
        if (!verif)
        {
            //TODO: Afficher un message d'erreur
            /*Lecon = _leconsRepository.GetLecon(LeconTitre);
            return Page();*/
        }

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostMoveExerciceAsync(string leconTitre, string exerciceTitre, string direction)
    {
        var verif = await _exercisesRepository.MoveExercice(leconTitre, exerciceTitre, direction);
        if (!verif)
        {
            //TODO: Afficher un message d'erreur
            /*Lecon = _leconsRepository.GetLecon(LeconTitre);
            return Page();*/
        }

        return RedirectToPage();
    }

    public class InputModel
    {
        [Required(ErrorMessage = "Le champ titre est requis")]
        [RegularExpression(@"^(?!.*<|>).*.{5,}$", ErrorMessage = "Le titre doit contenir au moins 5 caractères et ne doit pas inclure les symboles <>.")]
        public string Titre { get; set; }

        [RegularExpression(@"^(?!.*<|>).*.{5,}$", ErrorMessage = "La description doit contenir au moins 5 caractères et ne doit pas inclure les symboles <>.")]
        public string Description { get; set; }
    }
}

Puroguramu.App/Pages/HomeCours.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains;
using Puroguramu.Domains.Repository;
using Puroguramu.Infrastructures.dto;
using Status = Puroguramu.Domains.Status;

namespace Puroguramu.App.Pages;

public class HomeCours : PageModel
{
    private readonly ILeconsRepository _leconsRepository;
    private readonly UserManager<Utilisateurs> _userManager;

    public HomeCours(ILeconsRepository leconsRepository, UserManager<Utilisateurs> userManager)
    {
        _leconsRepository = leconsRepository;
        _userManager = userManager;
    }

    [BindProperty(SupportsGet = true)]
    public string TitreCours { get; set; }

    public List<Lecon> Lecons { get; set; }


    public async Task OnGetAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        Lecons = _leconsRepository.GetLeconsForCours(TitreCours,user.Id).ToList();
    }
}

Puroguramu.App/Pages/HomePage.cshtml.cs
using System.Collections;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains;
using Puroguramu.Domains.Repository;
using Puroguramu.Infrastructures.dto;

namespace Puroguramu.App.Pages;

public class HomePage : PageModel
{
    private readonly ICoursRepository _coursRepository;
    private readonly SignInManager<Utilisateurs> _signInManager; // Ajoutez cette ligne

    // Injectez SignInManager dans le constructeur
    public HomePage(ICoursRepository coursRepository, SignInManager<Utilisateurs> signInManager)
    {
        _coursRepository = coursRepository;
        _signInManager = signInManager;
    }

    public IEnumerable<Cour> Cours { get; set; }

    public IActionResult OnGet()
    {
        // Vérifie si l'utilisateur est déjà connecté
        if (!_signInManager.IsSignedIn(User))
        {
            // Si l'utilisateur est connecté, redirigez-le
            // Vous pouvez changer la redirection selon vos besoins
            return RedirectToPage("./Index");
        }

        // Chargez les leçons seulement si l'utilisateur n'est pas connecté
        Cours = _coursRepository.GetCours();

        // Continuez avec la page normalement pour les utilisateurs non connectés
        return Page();
    }
}

Puroguramu.App/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Puroguramu.Domains.Repository;
using Puroguramu.Infrastructures.dto;

namespace Puroguramu.App.Pages;

public class IndexModel : PageModel
{
    private readonly IExercisesRepository _exercisesRepository;
    private readonly ILeconsRepository _leconsRepository;
    private readonly SignInManager<Utilisateurs> _signInManager;

    public IndexModel(SignInManager<Utilisateurs> signInManager, ILeconsRepository leconsRepository, IExercisesRepository exercisesRepository)
    {
        _signInManager = signInManager;
        _leconsRepository = leconsRepository;
        _exercisesRepository = exercisesRepository;
    }

    public string? LeconsDispos { get; set; }

    public string? ExosDispos { get; set; }

    public int CountEtudiant { get; set; }

    public IActionResult OnGet()
    {
        // Vérifie si l'utilisateur est déjà connecté
        if (_signInManager.IsSignedIn(User))
        {
            // Redirige vers la page HomePage si l'utilisateur est déjà connecté
            return RedirectToPage("./DashBoard");
        }

        CountEtudiant = _signInManager.UserManager.Users.Count(e => e.Role == Role.Student);
        LeconsDispos = _leconsRepository.GetLecons().Count().ToString();
        ExosDispos = _exercisesRepository.GetExercisesCount().ToString();

        // Continue avec la page Index si l'utilisateur n'est pas connecté
        return Page();
    }
}

Puroguramu.App/Pages/DashBoard.cshtml
@page "/DashBoard"
@using Puroguramu.Infrastructures.dto
@model Puroguramu.App.Pages.DashBoard
@Html.AntiForgeryToken()


@{
    Layout = "_Layout";
    ViewData["Title"] = Model.TitreCours;
}

<div class="container mx-auto px-4 py-8">
    <h1 class="text-2xl font-bold text-center mb-6">Tableau de bord</h1>

    @if (Model.Lecons.Any())
    {
        <div class="space-y-4">
            @foreach (var lecon in Model.Lecons)
            {
                <a href="@Url.Page("/Lecons", new { LeconTitre = lecon.Titre })">
                    <div class="p-4 bg-white rounded-lg shadow-lg flex justify-between items-center mb-6 hover:bg-gray-100">
                        <div>
                            <h2 class="text-xl font-semibold">@lecon.Titre</h2>
                            <div class="text-sm font-medium mr-2">
                                @lecon.ExercicesFait / @lecon.ExercicesTotal
                                @if ((Role)ViewData["Role"]! != Role.Teacher)
                                {
                                    <p>Exercices réussis</p>
                                }
                                else
                                {
                                    <p>Étudiants</p>
                                }
                            </div>
                        </div>
                        <div class="flex items-center">

                            @if ((Role)ViewData["Role"]! == Role.Teacher)
                            {
                                <form method="post" asp-page-handler="MoveLecon" asp-route-leconTitre="@lecon.Titre"
                                      asp-route-direction="up">
                                    <button type="submit" class="text-blue-500 hover:text-blue-700 mr-2">
                                        <i class="fas fa-arrow-up"></i>
                                    </button>
                                </form>
                                <form method="post" asp-page-handler="MoveLecon" asp-route-leconTitre="@lecon.Titre"
                                      asp-route-direction="down">
                                    <button type="submit" class="text-blue-500 hover:text-blue-700 mr-2">
                                        <i class="fas fa-arrow-down"></i>
                                    </button>
                                </form>
                                <a href="@Url.Page("/CreateExercices", new { LeconTitre = lecon.Titre })"
                                   class="text-blue-500 hover:text-blue-700 mr-2">
                                    <i class="fas fa-plus"></i>
                                </a>
                                <form method="post" asp-page-handler="ChangeVisibility" asp-route-leconTitre="@lecon.Titre">
                                    <button type="submit" class="text-blue-500 hover:text-blue-700 mr-2">
                                        <i class="@(lecon.EstVisible ? "fas fa-eye" : "fas fa-eye-slash") rounded-full"></i>
                                    </button>
                                </form>
                                <a href="@Url.Page("/EditLecon", new { LeconTitre = lecon.Titre })" class="text-green-500 hover:text-green-700 mr-2">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <form method="post" asp-page-handler="DeleteLecon" asp-route-leconTitre="@lecon.Titre"
                                      onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette leçon?');">
                                    <button type="submit" class="text-red-500 hover:text-red-700">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            }
                        </div>
                    </div>
                </a>
            }
        </div>
    }
    else
    {
        <p class="text-center text-gray-600">Aucune leçon trouvée pour ce cours.</p>
    }

    @if ((Role)ViewData["Role"]! == Role.Teacher)
    {
        <div class="flex justify-center mt-8">
            <a href="@Url.Page("/CreateLecons")"
               class="px-6 py-2 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-150 ease-in-out">
                Créer
                une nouvelle leçon
            </a>
        </div>
    }
    else
    {
        <div class="flex justify-between items-center mt-8">
            <form method="post" asp-page-handler="ProchainExercice">
                <button type="submit" class="px-6 py-2 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-150 ease-in-out">Prochain Exercice</button>
            </form>
            <form method="post" asp-page-handler="ReprendreExercices">
                <button type="submit" class="px-6 py-2 bg-green-500 text-white font-semibold rounded-lg hover:bg-green-700 transition duration-150 ease-in-out">Reprendre Exercices</button>
            </form>
        </div>
    }
</div>

Puroguramu.App/Pages/EditLecon.cshtml
@page "/EditLecon/{LeconTitre}"
@model Puroguramu.App.Pages.EditLecon
@Html.AntiForgeryToken()


@{
    Layout = "_Layout";
    ViewData["Title"] = "Éditer " + Model.LeconTitre;
}

<div class="flex justify-center items-center min-h-screen">
    <div class="w-full max-w-md">
        <section class="bg-white shadow-md  border rounded px-8 pt-6 pb-8 mb-4">
            <form id="editLeconsForm" asp-route-returnUrl="@Model.ReturnUrl" method="post" class="space-y-4">
                <h2 class="text-lg font-semibold text-center">Éditer @Model.LeconTitre</h2>
                <hr class="my-2"/>
                <div asp-validation-summary="ModelOnly" class="text-red-500"></div>
                <div class="form-group">
                    <label asp-for="Input.Titre" class="block text-sm font-medium text-gray-700">Titre</label>
                    <input asp-for="Input.Titre"
                           class="mt-1 p-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                           aria-required="true"/>
                    <span asp-validation-for="Input.Titre" class="text-red-500 text-xs"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.Description" class="block text-sm font-medium text-gray-700">Description</label>
                    <input asp-for="Input.Description"
                           class="mt-1 p-2 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                           ♦ aria-required="true"/>
                    <span asp-validation-for="Input.Description" class="text-red-500 text-xs"></span>
                </div>
                <div class="flex justify-center">
                    <button id="editLeconsSubmit" type="submit" class="mt-2 w-full inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">Éditer</button>
                </div>
            </form>
        </section>
        @if (Model.Lecon.ExercicesList.Any())
        {
            <div class="bg-white shadow-md  border rounded px-8 pt-6 pb-8 mb-4">
                <h2 class="text-lg font-semibold text-center">List des exercices</h2>
                <hr class="my-2"/>
                @foreach (var exo in Model.Lecon.ExercicesList)
                {
                    <div class="p-4 m-4 bg-white rounded-lg shadow-lg flex justify-between items-center">
                        <div class="flex items-center">
                            <div>
                                <h2 class="text-xl font-semibold">@exo.Titre</h2>
                            </div>
                        </div>
                        <form method="post" asp-page-handler="MoveExercice" asp-route-leconTitre="@Model.LeconTitre"
                              asp-route-exerciceTitre="@exo.Titre"
                              asp-route-direction="up">
                            <button type="submit" class="text-blue-500 hover:text-blue-700 mr-2">
                                <i class="fas fa-arrow-up"></i>
                            </button>
                        </form>
                        <form method="post" asp-page-handler="MoveExercice" asp-route-leconTitre="@Model.LeconTitre"
                              asp-route-exerciceTitre="@exo.Titre"
                              asp-route-direction="down">
                            <button type="submit" class="text-blue-500 hover:text-blue-700 mr-2">
                                <i class="fas fa-arrow-down"></i>
                            </button>
                        </form>
                        <form method="post" asp-page-handler="ChangeVisibility" asp-route-leconTitre="@Model.LeconTitre"
                              asp-route-exerciceTitre="@exo.Titre">
                            <button type="submit" class="text-blue-500 hover:text-blue-700 mr-2">
                                <i class="@(exo.EstVisible ? "fas fa-eye" : "fas fa-eye-slash") rounded-full"></i>
                            </button>
                        </form>
                        <a href="@Url.Page("/EditExercice", new { Model.LeconTitre, ExerciceTitre = exo.Titre })"
                           class="text-green-500 hover:text-green-700 mr-2">
                            <i class="fas fa-edit"></i>
                        </a>
                        <form method="post" asp-page-handler="DeleteExercice" asp-route-leconTitre="@Model.LeconTitre"
                              asp-route-exerciceTitre="@exo.Titre"
                              onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette exercice?');">
                            <button type="submit" class="text-red-500 hover:text-red-700">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>

                    </div>
                }
            </div>
        }
        else
        {
            <p class="text-center text-gray-600">Aucun exercice trouvé pour cette leçon.</p>
        }

        <div class="flex justify-between items-center mt-8">
            <a href="@Url.Page("/CreateExercices", new { Model.LeconTitre })"
               class="px-6 py-2 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-150 ease-in-out">
                Créer
                un nouvel exercice
            </a>
        </div>
    </div>


</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}